#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("OnAir.Resource", IsApplication=true)]

namespace OnAir
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int blueclick = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int disabledText = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int greyheadertext = 2130968577;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int login_button = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int loginbox = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int monoandroidsplash = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int questionmark = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int signin = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int twitter = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int XamarinTitle = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070001
			public const int dialogImage = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int dialogLayout = 2131165184;
			
			// aapt resource value: 0x7f070009
			public const int listView1 = 2131165193;
			
			// aapt resource value: 0x7f070004
			public const int logIn = 2131165188;
			
			// aapt resource value: 0x7f070006
			public const int myDoors = 2131165190;
			
			// aapt resource value: 0x7f070008
			public const int myFilter = 2131165192;
			
			// aapt resource value: 0x7f070005
			public const int myUsers = 2131165189;
			
			// aapt resource value: 0x7f070003
			public const int password = 2131165187;
			
			// aapt resource value: 0x7f070007
			public const int textView1 = 2131165191;
			
			// aapt resource value: 0x7f070002
			public const int userName = 2131165186;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Login = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int User = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Users = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050005
			public const int authorizerUrl = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int baseUrl = 2131034116;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int some_hint = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int some_text = 2131034114;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Mono_Android_Theme_Splash = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
